---
title: "Getting Organized to Do Data Science"
author: |
        | Christopher Skovron
        | Northwestern University 
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  revealjs::revealjs_presentation: 
    theme: simple
    highlight: haddock
    center: false
    transition: none
    #css: reveal.css
    self_contained: false
---
          
          
## Get organized

- Doing Data Science 



## Understand your file structure


## Paths


## Setting a working directory


## Navigating, relational paths


## Good organizational principles


## Good and bad file names


## One script per task


## Mind the order 


## Your audiences, in decreasing order

- Your future self
- Your collaborators
- Replicators 


## Commenting

- Messages to all of your audiences 
- Say what you're doing in plain words and why you're doing it



## Version control 

- Simplest version -- lets you revert to the past
- Track changes made by collaborators
- Document your contributions to code 


## Version control options

- Git/github
- Dropbox version control





## Tidy data principles 

- Every data task will be different, but tidy data principles will help you keep organized
- Much of your workflow will be getting data inputs into a tidy format
- From the beginning, lay out what you need your dataset to look like to do the analyses you want, then work backward from there

## Long data

## Wide data

## Relational data 




## Where to work? Development environments


What folders should you have
